### PR TITLE
 Add support for Python 3.5, 3.6, 3.7, PyPy and PyPy3.

### PR DESCRIPTION
**Pull request by icemac**
I also added support for coveralls.io. The package has to be enabled there so the coverage can show up here.

### CODE REVIEW

**Review by mauritsvanrees — APPROVED** [review]
LGTM

**Comment by icemac** [comment]
Thank you.

**Comment by reinout** [comment]
@icemac: I've activated coveralls: https://coveralls.io/github/reinout/z3c.recipe.usercrontab

**Comment by icemac** [comment]
@reinout Nice. Is it time for a new release?

**Comment by reinout** [comment]
I've taken zest.releaser for a spin: 1.5 is out now :-)

**Comment by icemac** [comment]
@reinout Thank you very much!

**Pull request merged**
